CREATE TABLE artists (
  artist_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  artist_name VARCHAR(255),
  genre_name VARCHAR(100)
);

CREATE TABLE songs (
  song_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  song_name VARCHAR(100) DEFAULT 'no song title',
  album_name VARCHAR(100) DEFAULT 'no album title',
  artist INTEGER REFERENCES artists(artist_id) NOT NULL
);

CREATE TABLE concerts (
  concert_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  concert_name VARCHAR(255),
  concert_date DATE
);

-- join table
CREATE TABLE artists_concerts (
  artist_id INTEGER REFERENCES artists(artist_id),
  concert_id INTEGER REFERENCES concerts(concert_id),
  scheduled_start_at TIME,
  scheduled_end_at TIME,
  PRIMARY KEY (artist_id, concert_id)
);