create table authors (
	author_id INTEGER primary key generated by default as identity,
	author_name varchar(255),
	nationality varchar(255)
);

create table books (
	book_id INTEGER primary key generated by default as identity,
	title varchar(255),
	publication_year INTEGER,
	in_stock boolean default true,
	author_id INTEGER references authors(author_id)
);

create table genres (
	genre_id INTEGER primary key generated by default as identity,
	genre_name VARCHAR(100)
);

create table books_genres (
	book_id INTEGER references books(book_id),
	genre_id INTEGER references genres(genre_id),
	primary key (book_id, genre_id)
);


select count(*) from authors a inner join books b on a.author_id = b.author_id where b.publication_year < 2000;

select count(*) from authors a inner join books b on a.author_id = b.author_id where a.author_name = 'Leo Tolstoy';

select * from authors a inner join books b on a.author_id = b.author_id 
where length(b.title) > 25;

select * from authors a inner join books b on a.author_id = b.author_id where b.publication_year < 2005 and a.nationality != 'United States of America';

select *
from books_genres bg 
inner join genres g on bg.genre_id = g.genre_id
inner join books b on bg.book_id = b.book_id
inner join authors a on b.author_id = a.author_id
where a.author_name = 'Leo Tolstoy' and g.genre_name in ('autobiography', 'history');

select * from authors a inner join books b on a.author_id = b.author_id where a.author_name = 'Amy Tan';

select * from authors a inner join books b on a.author_id = b.author_id where a.nationality in ('China', 'Turkey');

select a.author_name, a.nationality, b.* from authors a inner join books b on a.author_id = b.author_id where b.in_stock = false;
